//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STR_CajaChica_Entregas.DL.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries_SQL_HANA_CCH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries_SQL_HANA_CCH() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STR_CajaChica_Entregas.DL.Resources.Queries_SQL_HANA_CCH", typeof(Queries_SQL_HANA_CCH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [@STR_CCHAPRDET] SET U_CC_STDO = &apos;?&apos;,U_CC_SLDO = &apos;?&apos; WHERE U_CC_CJCH = &apos;?&apos; AND U_CC_NMCC = &apos;?&apos;|UPDATE &quot;@STR_CCHAPRDET&quot; SET &quot;U_CC_STDO&quot; = &apos;?&apos;,&quot;U_CC_SLDO&quot; = &apos;?&apos; WHERE &quot;U_CC_CJCH&quot; = &apos;?&apos; AND &quot;U_CC_NMCC&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ActEstadoNumerosCCH {
            get {
                return ResourceManager.GetString("ActEstadoNumerosCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_ActualizarDatosPorReaperturaCCH &apos;?&apos;,&apos;?&apos;|CALL STR_SP_ActualizarDatosPorReaperturaCCH(&apos;?&apos;,&apos;?&apos;).
        /// </summary>
        internal static string ActEstadoReapertura {
            get {
                return ResourceManager.GetString("ActEstadoReapertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [@STR_CCHCRGDET] SET U_CC_DEDC = &apos;?&apos;,U_CC_ESTD = &apos;?&apos; WHERE DocEntry = &apos;?&apos; AND LineId IN (?)|UPDATE &quot;@STR_CCHCRGDET&quot; SET &quot;U_CC_DEDC&quot; = &apos;?&apos;,&quot;U_CC_ESTD&quot; = &apos;?&apos; WHERE &quot;DocEntry&quot; = &apos;?&apos; AND &quot;LineId&quot; IN (?).
        /// </summary>
        internal static string ActualizarEstadoCreacion {
            get {
                return ResourceManager.GetString("ActualizarEstadoCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_INT_AgruparLineasCCH &apos;?&apos;,&apos;?&apos;,&apos;?&apos;,&apos;?&apos;,&apos;?&apos;|CALL STR_SP_INT_AgruparLineasCCH( &apos;?&apos;,&apos;?&apos;,&apos;?&apos;,&apos;?&apos;,&apos;?&apos;).
        /// </summary>
        internal static string AgruparLineasCCH {
            get {
                return ResourceManager.GetString("AgruparLineasCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_GenerarCodigo_CCH_EAR &apos;?&apos;,&apos;?&apos;|CALL STR_SP_GenerarCodigo_CCH_EAR(&apos;?&apos;,&apos;?&apos;).
        /// </summary>
        internal static string GenerarCodigoCCH {
            get {
                return ResourceManager.GetString("GenerarCodigoCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_LOC_Create_OPCH_XML&apos;?&apos;,&apos;?&apos;,&apos;?&apos;|CALL STR_SP_CREATE_OPCH_XML(&apos;?&apos;,&apos;?&apos;,&apos;?&apos;).
        /// </summary>
        internal static string GenerarDocumentoXML {
            get {
                return ResourceManager.GetString("GenerarDocumentoXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT T0.Account,T1.ActCurr FROM DSC1 T0 INNER JOIN OACT T1 ON T0.GLAccount = T1.AcctCode WHERE BankCode =&apos;?&apos; AND ActCurr = &apos;?&apos;|SELECT T0.&quot;Account&quot;,T1.&quot;ActCurr&quot; FROM DSC1 T0 INNER JOIN OACT T1 ON 
        ///T0.&quot;GLAccount&quot; = T1.&quot;AcctCode&quot; WHERE &quot;BankCode&quot; =&apos;?&apos; AND &quot;ActCurr&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ObtCuentaBanco {
            get {
                return ResourceManager.GetString("ObtCuentaBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT GLAccount,(SELECT ActCurr FROM OACT WHERE AcctCode=GLAccount),(SELECT AcctName FROM OACT WHERE AcctCode=GLAccount) FROM DSC1
        ///WHERE BankCode = &apos;?&apos; AND Account = &apos;?&apos;|SELECT &quot;GLAccount&quot;,(SELECT &quot;ActCurr&quot; FROM OACT WHERE &quot;AcctCode&quot;=&quot;GLAccount&quot;),(SELECT &quot;AcctName&quot; FROM OACT WHERE &quot;AcctCode&quot;=&quot;GLAccount&quot;)
        ///FROM DSC1 WHERE &quot;BankCode&quot; = &apos;?&apos; AND &quot;Account&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ObtCuentadeBancoPropio {
            get {
                return ResourceManager.GetString("ObtCuentadeBancoPropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U_BPP_ACCT FROM [@BPP_CAJASCHICAS] WHERE Code = &apos;?&apos;|SELECT &quot;U_BPP_ACCT&quot; FROM &quot;@BPP_CAJASCHICAS&quot; WHERE &quot;Code&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ObtCuentadeCajaChica {
            get {
                return ResourceManager.GetString("ObtCuentadeCajaChica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT FormatCode,AcctName FROM OACT WHERE AcctCode = &apos;?&apos;|SELECT &quot;FormatCode&quot;,&quot;AcctName&quot; FROM OACT WHERE &quot;AcctCode&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ObtDatosCuentaCCH {
            get {
                return ResourceManager.GetString("ObtDatosCuentaCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CFWId, CFWName FROM OCFW WHERE &quot;Postable&quot; = &apos;Y&apos; | SELECT &quot;CFWId&quot;,&quot;CFWName&quot; FROM OCFW WHERE &quot;Postable&quot; = &apos;Y&apos;.
        /// </summary>
        internal static string ObtFlujodeCaja {
            get {
                return ResourceManager.GetString("ObtFlujodeCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT  T0.BankCode,BankName FROM ODSC T0 INNER JOIN DSC1 T1 ON T0.BankCode = T1.BankCode inner join OACT T3 ON T1.GLAccount = T3.AcctCode WHERE T3.Postable = &apos;Y&apos;|SELECT DISTINCT  T0.&quot;BankCode&quot;,&quot;BankName&quot; FROM ODSC T0 INNER JOIN DSC1 T1 ON T0.&quot;BankCode&quot; = T1.&quot;BankCode&quot; 
        ///INNER JOIN OACT T3 ON T1.&quot;GLAccount&quot; = T3.&quot;AcctCode&quot; WHERE T3.&quot;Postable&quot; = &apos;Y&apos;.
        /// </summary>
        internal static string ObtListadeBancos {
            get {
                return ResourceManager.GetString("ObtListadeBancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CurrCode,CurrName FROM OCRN | SELECT &quot;CurrCode&quot;,&quot;CurrName&quot; FROM OCRN.
        /// </summary>
        internal static string ObtMonedas {
            get {
                return ResourceManager.GetString("ObtMonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &quot;U_CC_MNAP&quot; FROM &quot;@STR_CCHAPRDET&quot; WHERE &quot;U_CC_CJCH&quot; = &apos;?&apos; AND &quot;U_CC_NMCC&quot; = &apos;?&apos; |SELECT &quot;U_CC_MNAP&quot; FROM &quot;@STR_CCHAPRDET&quot; WHERE &quot;U_CC_CJCH&quot; = &apos;?&apos; AND &quot;U_CC_NMCC&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ObtMontoApertura {
            get {
                return ResourceManager.GetString("ObtMontoApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_NumerosCajaChicaActivos &apos;?&apos;|CALL STR_SP_NumerosCajaChicaActivos(&apos;?&apos;).
        /// </summary>
        internal static string ObtNumerosdeCajaChicaActivos {
            get {
                return ResourceManager.GetString("ObtNumerosdeCajaChicaActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_LOC_PagosRealizadosPorNumero_CCH_EAR &apos;?&apos;,&apos;?&apos;,&apos;?&apos;|CALL STR_SP_LOC_PagosRealizadosPorNumero_CCH_EAR(&apos;?&apos;,&apos;?&apos;,&apos;?&apos;).
        /// </summary>
        internal static string ObtPagosPorNumerodeCajaChica {
            get {
                return ResourceManager.GetString("ObtPagosPorNumerodeCajaChica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_SaldoNumerosCajaChica &apos;?&apos;|CALL STR_SP_SaldoNumerosCajaChica(&apos;?&apos;).
        /// </summary>
        internal static string ObtSaldoCajaChica {
            get {
                return ResourceManager.GetString("ObtSaldoCajaChica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT T0.U_BPP_TDTD,T0.U_BPP_TDDD FROM [@BPP_TPODOC] T0 INNER JOIN [@BPP_TIPOXFORM] T1 ON T0.U_BPP_TDTD = T1.U_BPP_Tipo WHERE T1.U_BPP_Form = &apos;141&apos;|SELECT DISTINCT T0.&quot;U_BPP_TDTD&quot;,T0.&quot;U_BPP_TDDD&quot; FROM &quot;@BPP_TPODOC&quot; T0 
        ///INNER JOIN &quot;@BPP_TIPOXFORM&quot; T1 ON T0.&quot;U_BPP_TDTD&quot; = T1.&quot;U_BPP_Tipo&quot; 
        ///WHERE T1.&quot;U_BPP_Form&quot; = &apos;141&apos;.
        /// </summary>
        internal static string ObtTiposdeDocumentos {
            get {
                return ResourceManager.GetString("ObtTiposdeDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_LOC_InfoTotalesPorCargaDocumentosCCH &apos;?&apos;|CALL STR_SP_LOC_InfoTotalesPorCargaDocumentosCCH(&apos;?&apos;).
        /// </summary>
        internal static string ObtTotalesXCarga {
            get {
                return ResourceManager.GetString("ObtTotalesXCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U_BPP_APER FROM [@BPP_CAJASCHICASACC] WHERE U_BPP_USER = &apos;?&apos; AND Code = &apos;?&apos;|SELECT &quot;U_BPP_APER&quot; FROM &quot;@BPP_CAJASCHICASACC&quot; WHERE &quot;U_BPP_USER&quot; = &apos;?&apos; AND &quot;Code&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ValidarAperturaCCH {
            get {
                return ResourceManager.GetString("ValidarAperturaCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U_BPP_CRGD FROM [@BPP_CAJASCHICASACC] WHERE U_BPP_USER = &apos;?&apos; AND Code = &apos;?&apos;|SELECT &quot;U_BPP_CRGD&quot; FROM &quot;@BPP_CAJASCHICASACC&quot; WHERE &quot;U_BPP_USER&quot; = &apos;?&apos; AND &quot;Code&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ValidarCargaCCH {
            get {
                return ResourceManager.GetString("ValidarCargaCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U_BPP_CRGD FROM [@BPP_CAJASCHICASACC] WHERE U_BPP_USER = &apos;?&apos; AND Code = &apos;?&apos;|SELECT &quot;U_BPP_CRCG&quot; FROM &quot;@BPP_CAJASCHICASACC&quot; WHERE &quot;U_BPP_USER&quot; = &apos;?&apos; AND &quot;Code&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ValidarCerrarCargaCCH {
            get {
                return ResourceManager.GetString("ValidarCerrarCargaCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U_BPP_CNTD FROM [@BPP_CAJASCHICASACC] WHERE U_BPP_USER = &apos;?&apos; AND Code = &apos;?&apos;|SELECT &quot;U_BPP_CNTD&quot; FROM &quot;@BPP_CAJASCHICASACC&quot; WHERE &quot;U_BPP_USER&quot; = &apos;?&apos; AND &quot;Code&quot; = &apos;?&apos;.
        /// </summary>
        internal static string ValidarContabCCH {
            get {
                return ResourceManager.GetString("ValidarContabCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_CantidadNumerosdeCajaChica &apos;?&apos; |CALL STR_SP_CantidadNumerosdeCajaChica (&apos;?&apos;).
        /// </summary>
        internal static string VerificarCantidadNrosCCH {
            get {
                return ResourceManager.GetString("VerificarCantidadNrosCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U_CC_SLDO,U_CC_STDO FROM [@STR_CCHAPRDET] WHERE U_CC_CJCH = &apos;?&apos; AND U_CC_NMCC = &apos;?&apos;|SELECT &quot;U_CC_SLDO&quot;,&quot;U_CC_STDO&quot; FROM &quot;@STR_CCHAPRDET&quot; WHERE &quot;U_CC_CJCH&quot; = &apos;?&apos; AND &quot;U_CC_NMCC&quot; = &apos;?&apos;.
        /// </summary>
        internal static string VerificarEstadoySaldoNroCCH {
            get {
                return ResourceManager.GetString("VerificarEstadoySaldoNroCCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC STR_SP_VERIFICAR_DOCUMENTO_EXISTENTE &apos;?&apos;,&apos;?&apos;|CALL STR_SP_VERIFICAR_DOCUMENTO_EXISTENTE(&apos;?&apos;,&apos;?&apos;).
        /// </summary>
        internal static string VerificarExisteDocumento {
            get {
                return ResourceManager.GetString("VerificarExisteDocumento", resourceCulture);
            }
        }
    }
}
